### ISSUE TITLE
compilation fails with phoenix_live_view 0.18

### ISSUE THREAD

**Issue by kevinschweikert** [frerich/underthehood#2]
```shell
== Compilation error in file lib/underthehood.ex ==
** (CompileError) lib/underthehood.ex:14: cannot import Phoenix.LiveView.Helpers.live_component/1 because it is undefined or private
    (elixir 1.14.2) src/elixir_import.erl:91: :elixir_import.calculate/6
    (elixir 1.14.2) src/elixir_import.erl:22: :elixir_import.import/4
    (stdlib 4.1.1) lists.erl:1462: :lists.mapfoldl_1/3
    (stdlib 4.1.1) lists.erl:1463: :lists.mapfoldl_1/3
    (elixir 1.14.2) expanding macro: Kernel.if/2
```

In [this line](https://github.com/frerich/underthehood/blob/c10070c0b5b41cd4fd7d5a9d61599c48ce0072d3/lib/underthehood.ex#L11 ) there is an import for `live_component/1`

```elixir
import Phoenix.LiveView.Helpers, only: [live_component: 1]
```

This function was moved to `Phoenix.Component`. I couldn't figure out how to import it conditionally, depending on the LiveView version. If anybody has a hint, I'll gladly do a PR.

**Comment by frerich** [comment]
Interesting! There is a function called [Kernel.function_exported?](https://hexdocs.pm/elixir/Kernel.html#function_exported?/3) which can be used to test if some module is loaded and contains a function with a given arity.

Maybe this could be used to do something like

```elixir
if function_exported?(Phoenix.LiveView.Helpers, :live_component, 1) do
  import Phoenix.LiveView.Helpers, only: [live_component: 1]
else
  ...do whatever needs to be done for Phoenix 1.7...
end
```
